// generated by go-immutables

package api_content

type ContentServiceBuilder interface {
	Build() ContentService

	SetDataStore(value map[string]Content) ContentServiceBuilder

}

type contentServiceBuilder struct {
	target ContentService
}

func NewContentServiceBuilder() ContentServiceBuilder {
	return &contentServiceBuilder{
		target: ContentService{},
	}
}

func (b *contentServiceBuilder) SetDataStore(value map[string]Content) ContentServiceBuilder {
	b.target.dataStore = value
	return b
}

func (b *contentServiceBuilder) Build() ContentService {
	return b.target
}