// generated by go-immutables

package api_content

type CreateContentResponseBuilder interface {
	Build() CreateContentResponse

	SetContent(value Content) CreateContentResponseBuilder

}

type createContentResponseBuilder struct {
	target CreateContentResponse
}

func NewCreateContentResponseBuilder() CreateContentResponseBuilder {
	return &createContentResponseBuilder{
		target: CreateContentResponse{},
	}
}

func (b *createContentResponseBuilder) SetContent(value Content) CreateContentResponseBuilder {
	b.target.content = value
	return b
}

func (b *createContentResponseBuilder) Build() CreateContentResponse {
	return b.target
}