// generated by go-immutables

package api_content

type CreateContentRequestBuilder interface {
	Build() CreateContentRequest

	SetTitle(value string) CreateContentRequestBuilder

	SetBody(value map[ContentFormat]string) CreateContentRequestBuilder

	SetSummary(value string) CreateContentRequestBuilder

}

type createContentRequestBuilder struct {
	target CreateContentRequest
}

func NewCreateContentRequestBuilder() CreateContentRequestBuilder {
	return &createContentRequestBuilder{
		target: CreateContentRequest{},
	}
}

func (b *createContentRequestBuilder) SetTitle(value string) CreateContentRequestBuilder {
	b.target.title = value
	return b
}

func (b *createContentRequestBuilder) SetBody(value map[ContentFormat]string) CreateContentRequestBuilder {
	b.target.body = value
	return b
}

func (b *createContentRequestBuilder) SetSummary(value string) CreateContentRequestBuilder {
	b.target.summary = value
	return b
}

func (b *createContentRequestBuilder) Build() CreateContentRequest {
	return b.target
}